export const categoryAndSubCategory = {
  'Health & Fitness': [
    'Aging',
    'Alternative Medicine',
    'Beauty, Grooming & Style',
    "Children's Health",
    'Disease & Ailments'
  ],
  'Computers & Tech': [
    'Computer Hardware',
    'Computer Software',
    'Internet & Web',
    'Mobile Phones & Tablets',
    'Networking & Internet Tools',
    'Operating Systems',
    'Programming & Tech Skills',
    'Software',
    'Tech News',
    'Tech Reviews',
    'Tech Support',
    'Tech Tips'
  ],
  'Business & Finance': [
    'Accounting & Finance',
    'Business News',
    'Business Skills',
    'Careers',
    'Economics',
    'Entrepreneurship',
    'Investing',
    'Management',
    'Marketing',
    'Personal Finance',
    'Small Business',
    'Taxes',
    'Venture Capital'
  ],
  'Food & Drink': [
    'Cooking',
    'Food & Drink News',
    'Food & Drink Reviews',
    'Food & Drink Shopping',
    'Food & Drink Tips',
    'Health & Diet',
    'Recipes',
    'Restaurants',
    'Special Diets',
    'Vitamins & Supplements'
  ],
  'Home & Garden': [
    'Appliances',
    'Arts & Crafts',
    'Automotive',
    'Bath & Beauty',
    'Bed & Bath',
    'Cooking & Dining',
    'DIY & Tools',
    'Entertaining',
    'Furniture',
    'Home & Garden News',
    'Home & Garden Reviews',
    'Home & Garden Shopping',
    'Home & Garden Tips',
    'Home Decor',
    'Home Improvement',
    'Interior Design',
    'Kitchen & Dining',
    'Outdoors',
    'Patio & Garden',
    'Pet Care',
    'Plants',
    'Tools & Home Improvement'
  ],
  'Science & Nature': [
    'Astronomy',
    'Biology',
    'Chemistry',
    'Earth Sciences',
    'Environment',
    'Geography',
    'Geology',
    'Life Sciences',
    'Mathematics',
    'Physics',
    'Space',
    'Weather'
  ],
  'Sports & Recreation': [
    'Baseball',
    'Basketball',
    'Cricket',
    'Cycling',
    'Football',
    'Golf',
    'Hockey',
    'Motorsport',
    'Rugby',
    'Running',
    'Soccer',
    'Swimming',
    'Tennis',
    'Volleyball',
    'Wrestling'
  ],
  Travel: [
    'Adventure Travel',
    'Air Travel',
    'Cruises',
    'Hotels',
    'Travel News',
    'Travel Guides'
  ]
};
export const language = [
  'English',
  'Marathi',
  'Hindi',
  'Gujarati',
  'Bengali',
  'Punjabi',
  'Kannada',
  'Tamil',
  'Telugu',
  'Malayalam',
  'Oriya',
  'Urdu',
  'Konkani',
  'Sindhi',
  'Assamese',
  'Bodo',
  'Dogri',
  'Kashmiri',
  'Konkani',
  'Manipuri',
  'Maithili',
  'Nepali',
  'Sanskrit',
  'Santali',
  'Sindhi',
  'Khasi',
  'Konkani',
  'Kurukh',
  'Kutchi',
  'Lepcha',
  'Magahi',
  'Maithili',
  'Marwari'
];
